version: '2.2'
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data1:/usr/share/elasticsearch/data
    ports:
      - 29200:9200
      - 29300:9300
    networks:
      - esnet

networks:
  esnet: