version: '3.3'

services:
  rabbit:
    image: rabbitmq:management
    restart: always
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "lsAPPLICATION"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/test"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    #volumes:
    #  - "./rabbit/plugins:/etc/rabbitmq/enabled_plugins"