//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.wx.message.ImgServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImgServiceReference.UploadServiceSoap")]
    public interface UploadServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        com.wx.message.ImgServiceReference.HelloWorldResponse HelloWorld(com.wx.message.ImgServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<com.wx.message.ImgServiceReference.HelloWorldResponse> HelloWorldAsync(com.wx.message.ImgServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Up", ReplyAction="*")]
        com.wx.message.ImgServiceReference.UpResponse Up(com.wx.message.ImgServiceReference.UpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Up", ReplyAction="*")]
        System.Threading.Tasks.Task<com.wx.message.ImgServiceReference.UpResponse> UpAsync(com.wx.message.ImgServiceReference.UpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public com.wx.message.ImgServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(com.wx.message.ImgServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public com.wx.message.ImgServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(com.wx.message.ImgServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Up", Namespace="http://tempuri.org/", Order=0)]
        public com.wx.message.ImgServiceReference.UpRequestBody Body;
        
        public UpRequest() {
        }
        
        public UpRequest(com.wx.message.ImgServiceReference.UpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string extName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int type;
        
        public UpRequestBody() {
        }
        
        public UpRequestBody(byte[] data, string filePath, string filename, string extName, int type) {
            this.data = data;
            this.filePath = filePath;
            this.filename = filename;
            this.extName = extName;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpResponse", Namespace="http://tempuri.org/", Order=0)]
        public com.wx.message.ImgServiceReference.UpResponseBody Body;
        
        public UpResponse() {
        }
        
        public UpResponse(com.wx.message.ImgServiceReference.UpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpResult;
        
        public UpResponseBody() {
        }
        
        public UpResponseBody(bool UpResult) {
            this.UpResult = UpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UploadServiceSoapChannel : com.wx.message.ImgServiceReference.UploadServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadServiceSoapClient : System.ServiceModel.ClientBase<com.wx.message.ImgServiceReference.UploadServiceSoap>, com.wx.message.ImgServiceReference.UploadServiceSoap {
        
        public UploadServiceSoapClient() {
        }
        
        public UploadServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.wx.message.ImgServiceReference.HelloWorldResponse com.wx.message.ImgServiceReference.UploadServiceSoap.HelloWorld(com.wx.message.ImgServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            com.wx.message.ImgServiceReference.HelloWorldRequest inValue = new com.wx.message.ImgServiceReference.HelloWorldRequest();
            inValue.Body = new com.wx.message.ImgServiceReference.HelloWorldRequestBody();
            com.wx.message.ImgServiceReference.HelloWorldResponse retVal = ((com.wx.message.ImgServiceReference.UploadServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.wx.message.ImgServiceReference.HelloWorldResponse> com.wx.message.ImgServiceReference.UploadServiceSoap.HelloWorldAsync(com.wx.message.ImgServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.wx.message.ImgServiceReference.HelloWorldResponse> HelloWorldAsync() {
            com.wx.message.ImgServiceReference.HelloWorldRequest inValue = new com.wx.message.ImgServiceReference.HelloWorldRequest();
            inValue.Body = new com.wx.message.ImgServiceReference.HelloWorldRequestBody();
            return ((com.wx.message.ImgServiceReference.UploadServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.wx.message.ImgServiceReference.UpResponse com.wx.message.ImgServiceReference.UploadServiceSoap.Up(com.wx.message.ImgServiceReference.UpRequest request) {
            return base.Channel.Up(request);
        }
        
        public bool Up(byte[] data, string filePath, string filename, string extName, int type) {
            com.wx.message.ImgServiceReference.UpRequest inValue = new com.wx.message.ImgServiceReference.UpRequest();
            inValue.Body = new com.wx.message.ImgServiceReference.UpRequestBody();
            inValue.Body.data = data;
            inValue.Body.filePath = filePath;
            inValue.Body.filename = filename;
            inValue.Body.extName = extName;
            inValue.Body.type = type;
            com.wx.message.ImgServiceReference.UpResponse retVal = ((com.wx.message.ImgServiceReference.UploadServiceSoap)(this)).Up(inValue);
            return retVal.Body.UpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.wx.message.ImgServiceReference.UpResponse> com.wx.message.ImgServiceReference.UploadServiceSoap.UpAsync(com.wx.message.ImgServiceReference.UpRequest request) {
            return base.Channel.UpAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.wx.message.ImgServiceReference.UpResponse> UpAsync(byte[] data, string filePath, string filename, string extName, int type) {
            com.wx.message.ImgServiceReference.UpRequest inValue = new com.wx.message.ImgServiceReference.UpRequest();
            inValue.Body = new com.wx.message.ImgServiceReference.UpRequestBody();
            inValue.Body.data = data;
            inValue.Body.filePath = filePath;
            inValue.Body.filename = filename;
            inValue.Body.extName = extName;
            inValue.Body.type = type;
            return ((com.wx.message.ImgServiceReference.UploadServiceSoap)(this)).UpAsync(inValue);
        }
    }
}
