version: '3.3'

services:
  mysql:
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root-1234
      MYSQL_DATABASE: hui
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa-1234
    volumes:
      - ./db:/var/lib/mysql
      #- ./sql/grant.sql:/docker-entrypoint-initdb.d/1-init.sql
      #- ./mysql/config/mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf