server:
  port: 9302

eureka:
  client:
    shouldFetchRegistry: false
    shouldRegisterWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9300/eureka/

spring:
  application:
    name: service-gateway

#下面的代码可以注释
zuul:
  sensitive-headers: true
  routes:
    S01:
      path: /S01/**
      serviceId: S01
    S02:
      path: /S02/**
      serviceId: S02
    identity:
      path: /identity/**
      serviceId: identity
    user:
      path: /user/**
      serviceId: user
    order:
      path: /order/**
      serviceId: order