version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db/
      - ./log/:/data/log/
      - ./init/:/docker-entrypoint-initdb.d/
volumes:
  mongodata:
    driver: local