spring:
  profiles:
    active: dev


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.182:3306/hui?characterEncoding=utf8&useSSL=false
    username: sa
    password: Sa123@456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true