version: '3.3'

services:
  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
  mysql:
    image: mysql:5.7
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root-1234
      MYSQL_DATABASE: hui
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa-1234
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/sql/grant.sql:/docker-entrypoint-initdb.d/1-init.sql
      #- ./mysql/config/mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  rabbit:
    image: rabbitmq:management
    restart: always
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "lsAPPLICATION"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/test"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    #volumes:
    #  - "./rabbit/plugins:/etc/rabbitmq/enabled_plugins"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
      #- ./mongo/config/configdb:/data/configdb
      - ./mongo/init:/docker-entrypoint-initdb.d
      #- ./mongo/config/myconfig.conf:/etc/mongo/mongod.conf